name: Build libraries

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_linux_wheels:
    name: Build Linux wheels
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: quay.io/pypa/manylinux2014_x86_64
            arch: "x86_64"
#          - image: quay.io/pypa/manylinux2014_aarch64
#            arch: "arm64"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install wget
        run: yum install -y wget

      - name: Run the build
        run: |
            git config --global --add safe.directory $(pwd)
            ./build.sh manylinux_x86_64.tar.gz

      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          path: hdf5/manylinux_x86_64.tar.gz
