name: Build libraries

on:
  push:
  create:
    tags:
      - '*'

jobs:
  build_macosx_x86_64:
    name: Build MacOSX (x86_64)
    runs-on: macOS-11
    env:
      ARTIFACT_NAME: macosx_x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install wget
        run: brew install wget

      - name: Run the build
        run: |
            git config --global --add safe.directory $(pwd)
            ./build_macosx.sh "x86_64" ${ARTIFACT_NAME}

      - name: Move tarballs
        run: | 
          mkdir artifacts
          mv libaec/libaec-*.tar.gz artifacts
          mv libhdf5/libhdf5-*.tar.gz artifacts

      - name: Upload tarballs
        uses: actions/upload-artifact@v3
        with:
          path: artifacts/*.tar.gz

  build_windows_x86_64:
    name: Build Windows (x86_64)
    runs-on: windows-2019
    env:
      ARTIFACT_NAME: windows_x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run the build
        run: |
            git config --global --add safe.directory $(pwd)
            ./build_windows.sh
        shell: bash

      - name: Upload tarballs
        uses: actions/upload-artifact@v3
        with:
          path: installed

  publish:
    name: Publish libraries
    needs: [build_macosx_x86_64, build_windows_x86_64]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Download macosx (x86_64) artifact
        uses: actions/download-artifact@v3
        with:
          path: dump

      - name: List artifacts
        run: ls -R
        working-directory: dump

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: "HDF5 binaries (1.12.2)"
          files: dump/*/*
