on:
  create:
    tags:
      - '*'

name: Create Docker images

jobs:
  create_docker:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         arch: [manylinux_x86_64, musllinux_x86_64, manylinux_x86_64_legacy]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Modify Dockerfile
        if: matrix.arch == 'manylinux_x86_64_legacy'
        run:
          cat manylinux_x86_64.dockerfile | sed "s/_2_34/2014/" > ${{ matrix.arch }}.dockerfile

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ github.repository }}/${{ matrix.arch }}:${{ github.ref_name }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ${{ matrix.arch }}.dockerfile
          registry: ghcr.io
